version: '3.7'
services:
  db:
    image: postgres:15
    container_name: monorepo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'